//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public string mancc { get; set; }
        public string tenncc { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
    }
}
