//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebAPIzEntities1 : DbContext
    {
        public WebAPIzEntities1()
            : base("name=WebAPIzEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHDBan> ChiTietHDBans { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBans { get; set; }
        public virtual DbSet<LoaiSP> LoaiSPs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        [DbFunction("WebAPIzEntities1", "F_GetAllHoaDonB")]
        public virtual IQueryable<F_GetAllHoaDonB_Result> F_GetAllHoaDonB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetAllHoaDonB_Result>("[WebAPIzEntities1].[F_GetAllHoaDonB]()");
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetAllLoaiSP")]
        public virtual IQueryable<F_GetAllLoaiSP_Result> F_GetAllLoaiSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetAllLoaiSP_Result>("[WebAPIzEntities1].[F_GetAllLoaiSP]()");
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetAllSP")]
        public virtual IQueryable<F_GetAllSP_Result> F_GetAllSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetAllSP_Result>("[WebAPIzEntities1].[F_GetAllSP]()");
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetDoanhThu")]
        public virtual IQueryable<F_GetDoanhThu_Result> F_GetDoanhThu(Nullable<System.DateTime> thoigianbd, Nullable<System.DateTime> thoigiankt)
        {
            var thoigianbdParameter = thoigianbd.HasValue ?
                new ObjectParameter("thoigianbd", thoigianbd) :
                new ObjectParameter("thoigianbd", typeof(System.DateTime));
    
            var thoigianktParameter = thoigiankt.HasValue ?
                new ObjectParameter("thoigiankt", thoigiankt) :
                new ObjectParameter("thoigiankt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetDoanhThu_Result>("[WebAPIzEntities1].[F_GetDoanhThu](@thoigianbd, @thoigiankt)", thoigianbdParameter, thoigianktParameter);
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetSPBanChay")]
        public virtual IQueryable<F_GetSPBanChay_Result> F_GetSPBanChay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetSPBanChay_Result>("[WebAPIzEntities1].[F_GetSPBanChay]()");
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetSPTheoKhoangGia")]
        public virtual IQueryable<F_GetSPTheoKhoangGia_Result> F_GetSPTheoKhoangGia(Nullable<double> giamin, Nullable<double> giamax)
        {
            var giaminParameter = giamin.HasValue ?
                new ObjectParameter("giamin", giamin) :
                new ObjectParameter("giamin", typeof(double));
    
            var giamaxParameter = giamax.HasValue ?
                new ObjectParameter("giamax", giamax) :
                new ObjectParameter("giamax", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetSPTheoKhoangGia_Result>("[WebAPIzEntities1].[F_GetSPTheoKhoangGia](@giamin, @giamax)", giaminParameter, giamaxParameter);
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetSPTheoMaLoai")]
        public virtual IQueryable<F_GetSPTheoMaLoai_Result> F_GetSPTheoMaLoai(string maloai)
        {
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetSPTheoMaLoai_Result>("[WebAPIzEntities1].[F_GetSPTheoMaLoai](@maloai)", maloaiParameter);
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetSPTheoTen")]
        public virtual IQueryable<F_GetSPTheoTen_Result> F_GetSPTheoTen(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetSPTheoTen_Result>("[WebAPIzEntities1].[F_GetSPTheoTen](@ten)", tenParameter);
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetSPTonKho")]
        public virtual IQueryable<F_GetSPTonKho_Result> F_GetSPTonKho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetSPTonKho_Result>("[WebAPIzEntities1].[F_GetSPTonKho]()");
        }
    
        [DbFunction("WebAPIzEntities1", "F_GetTKTheoMa")]
        public virtual IQueryable<F_GetTKTheoMa_Result> F_GetTKTheoMa(string manguoidung)
        {
            var manguoidungParameter = manguoidung != null ?
                new ObjectParameter("manguoidung", manguoidung) :
                new ObjectParameter("manguoidung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_GetTKTheoMa_Result>("[WebAPIzEntities1].[F_GetTKTheoMa](@manguoidung)", manguoidungParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SuaChiTietHDB(string mahoadon, string masp, Nullable<int> soluong, Nullable<double> thanhtien)
        {
            var mahoadonParameter = mahoadon != null ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(string));
    
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaChiTietHDB", mahoadonParameter, maspParameter, soluongParameter, thanhtienParameter);
        }
    
        public virtual int SuaHoaDonBan(string mahd, Nullable<System.DateTime> ngaydat, string hoten, string sdt, string diachinhanhang, Nullable<double> tongtientt)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var ngaydatParameter = ngaydat.HasValue ?
                new ObjectParameter("ngaydat", ngaydat) :
                new ObjectParameter("ngaydat", typeof(System.DateTime));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachinhanhangParameter = diachinhanhang != null ?
                new ObjectParameter("diachinhanhang", diachinhanhang) :
                new ObjectParameter("diachinhanhang", typeof(string));
    
            var tongtienttParameter = tongtientt.HasValue ?
                new ObjectParameter("tongtientt", tongtientt) :
                new ObjectParameter("tongtientt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaHoaDonBan", mahdParameter, ngaydatParameter, hotenParameter, sdtParameter, diachinhanhangParameter, tongtienttParameter);
        }
    
        public virtual int SuaLoaiSanPham(string maloai, string tenloai)
        {
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            var tenloaiParameter = tenloai != null ?
                new ObjectParameter("tenloai", tenloai) :
                new ObjectParameter("tenloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaLoaiSanPham", maloaiParameter, tenloaiParameter);
        }
    
        public virtual int SuaNguoiDung(string mand, string hoten, string email, string matkhau, string sdt, string diachi, Nullable<int> maquyen)
        {
            var mandParameter = mand != null ?
                new ObjectParameter("mand", mand) :
                new ObjectParameter("mand", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var maquyenParameter = maquyen.HasValue ?
                new ObjectParameter("maquyen", maquyen) :
                new ObjectParameter("maquyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNguoiDung", mandParameter, hotenParameter, emailParameter, matkhauParameter, sdtParameter, diachiParameter, maquyenParameter);
        }
    
        public virtual int SuaNhaCungCap(string mancc, string tenncc, string sdt, string diachi)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaNhaCungCap", manccParameter, tennccParameter, sdtParameter, diachiParameter);
        }
    
        public virtual int SuaSanPham(string masp, string tensp, string mota, Nullable<int> soluong, Nullable<double> dongia, string anh, string maloai)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(double));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(string));
    
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SuaSanPham", maspParameter, tenspParameter, motaParameter, soluongParameter, dongiaParameter, anhParameter, maloaiParameter);
        }
    
        public virtual int ThemChiTietHDB(string mahoadon, string masp, Nullable<int> soluong, Nullable<double> thanhtien)
        {
            var mahoadonParameter = mahoadon != null ?
                new ObjectParameter("mahoadon", mahoadon) :
                new ObjectParameter("mahoadon", typeof(string));
    
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemChiTietHDB", mahoadonParameter, maspParameter, soluongParameter, thanhtienParameter);
        }
    
        public virtual int ThemHoaDonBan(string mahd, Nullable<System.DateTime> ngaydat, string hoten, string sdt, string diachinhanhang, Nullable<double> tongtientt)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var ngaydatParameter = ngaydat.HasValue ?
                new ObjectParameter("ngaydat", ngaydat) :
                new ObjectParameter("ngaydat", typeof(System.DateTime));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachinhanhangParameter = diachinhanhang != null ?
                new ObjectParameter("diachinhanhang", diachinhanhang) :
                new ObjectParameter("diachinhanhang", typeof(string));
    
            var tongtienttParameter = tongtientt.HasValue ?
                new ObjectParameter("tongtientt", tongtientt) :
                new ObjectParameter("tongtientt", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemHoaDonBan", mahdParameter, ngaydatParameter, hotenParameter, sdtParameter, diachinhanhangParameter, tongtienttParameter);
        }
    
        public virtual int ThemLoaiSP(string maloai, string tenloai)
        {
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            var tenloaiParameter = tenloai != null ?
                new ObjectParameter("tenloai", tenloai) :
                new ObjectParameter("tenloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemLoaiSP", maloaiParameter, tenloaiParameter);
        }
    
        public virtual int ThemNguoiDung(string mand, string hoten, string email, string matkhau, string sdt, string diachi, Nullable<int> maquyen)
        {
            var mandParameter = mand != null ?
                new ObjectParameter("mand", mand) :
                new ObjectParameter("mand", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var maquyenParameter = maquyen.HasValue ?
                new ObjectParameter("maquyen", maquyen) :
                new ObjectParameter("maquyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNguoiDung", mandParameter, hotenParameter, emailParameter, matkhauParameter, sdtParameter, diachiParameter, maquyenParameter);
        }
    
        public virtual int ThemNhaCungCap(string mancc, string tenncc, string sdt, string diachi)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemNhaCungCap", manccParameter, tennccParameter, sdtParameter, diachiParameter);
        }
    
        public virtual int ThemSanPham(string masp, string tensp, string mota, Nullable<int> soluong, Nullable<double> dongia, string anh, string maloai)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(double));
    
            var anhParameter = anh != null ?
                new ObjectParameter("anh", anh) :
                new ObjectParameter("anh", typeof(string));
    
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemSanPham", maspParameter, tenspParameter, motaParameter, soluongParameter, dongiaParameter, anhParameter, maloaiParameter);
        }
    
        public virtual int XoaChiTietHDBan(string mahd, string masp)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaChiTietHDBan", mahdParameter, maspParameter);
        }
    
        public virtual int XoaHoaDonB(string mahd)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaHoaDonB", mahdParameter);
        }
    
        public virtual int XoaNhaCungCap(string mancc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaNhaCungCap", manccParameter);
        }
    
        public virtual int XoaSanPham(string masp)
        {
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaSanPham", maspParameter);
        }
    }
}
