//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SanPham
    {
        [DisplayName("Mã s?n ph?m")]
        public string masp { get; set; }

        [DisplayName("Tên s?n ph?m")]
        public string tensp { get; set; }

        [DisplayName("Mô t?")]
        public string mota { get; set; }

        [DisplayName("S? l??ng")]
        public int soluong { get; set; }

        [DisplayName("??n giá")]
        public double dongia { get; set; }

        [DisplayName("?nh")]
        public string anh { get; set; }

        [DisplayName("Mã lo?i")]
        public string maloai { get; set; }
    }
}
