//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrioleCosmeticServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHDBan
    {
        public string mahd { get; set; }
        public string masp { get; set; }
        public int soluong { get; set; }
        public double thanhtien { get; set; }
    }
}
