//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrioleCosmeticServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        public string mahd { get; set; }
        public System.DateTime ngaydat { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string diachinhanhang { get; set; }
        public double tongtientt { get; set; }

        public List<ChiTietHDBan> chiTietHDBans { get; set; }
    }
}
