//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrioleCosmeticServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.ChiTietHoaDonBs = new HashSet<ChiTietHDBan>();
        }

        public string mahd { get; set; }
        public System.DateTime ngaydat { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string diachinhanhang { get; set; }
        public double tongtientt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<ChiTietHDBan> ChiTietHoaDonBs { get; set; }

    }
}
